# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(601, 443)
        self.listWidget = QtWidgets.QListWidget(MainWidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 40, 131, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.dial = QtWidgets.QDial(MainWidget)
        self.dial.setGeometry(QtCore.QRect(180, 290, 121, 121))
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(MainWidget)
        self.dial_2.setGeometry(QtCore.QRect(390, 290, 121, 121))
        self.dial_2.setNotchesVisible(True)
        self.dial_2.setObjectName("dial_2")
        self.label_5 = QtWidgets.QLabel(MainWidget)
        self.label_5.setGeometry(QtCore.QRect(161, 51, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(MainWidget)
        self.label_6.setGeometry(QtCore.QRect(210, 240, 54, 12))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(MainWidget)
        self.label_7.setGeometry(QtCore.QRect(420, 240, 54, 12))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(MainWidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(MainWidget)
        self.label_8.setGeometry(QtCore.QRect(210, 280, 54, 12))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(MainWidget)
        self.label_9.setGeometry(QtCore.QRect(420, 280, 54, 12))
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(MainWidget)
        self.label_10.setGeometry(QtCore.QRect(161, 69, 71, 16))
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 611, 16))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_11 = QtWidgets.QLabel(MainWidget)
        self.label_11.setGeometry(QtCore.QRect(310, 30, 54, 12))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(MainWidget)
        self.label_12.setGeometry(QtCore.QRect(460, 30, 54, 12))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.textBrowser = QtWidgets.QTextBrowser(MainWidget)
        self.textBrowser.setGeometry(QtCore.QRect(388, 60, 211, 159))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Form"))
        self.label_5.setText(_translate("MainWidget", "MAC地址："))
        self.label_6.setText(_translate("MainWidget", "亮度"))
        self.label_7.setText(_translate("MainWidget", "色温"))
        self.pushButton.setText(_translate("MainWidget", "开关"))
        self.label_10.setText(_translate("MainWidget", "状态："))
        self.label.setText(_translate("MainWidget", "协议："))
        self.label_2.setText(_translate("MainWidget", "状态："))
        self.label_3.setText(_translate("MainWidget", "上传时间："))
        self.label_4.setText(_translate("MainWidget", "设备数："))


